/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CLOSE_DISCRIMINATOR = new Uint8Array([
  98, 165, 201, 177, 108, 65, 206, 96,
]);

export function getCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_DISCRIMINATOR);
}

export type CloseInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountUserVault extends string | AccountMeta<string> = string,
  TAccountUserVaultLamports extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountUserVault extends string
        ? WritableAccount<TAccountUserVault>
        : TAccountUserVault,
      TAccountUserVaultLamports extends string
        ? WritableAccount<TAccountUserVaultLamports>
        : TAccountUserVaultLamports,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseInstructionDataArgs = {};

export function getCloseInstructionDataEncoder(): FixedSizeEncoder<CloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_DISCRIMINATOR }),
  );
}

export function getCloseInstructionDataDecoder(): FixedSizeDecoder<CloseInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseInstructionDataCodec(): FixedSizeCodec<
  CloseInstructionDataArgs,
  CloseInstructionData
> {
  return combineCodec(
    getCloseInstructionDataEncoder(),
    getCloseInstructionDataDecoder(),
  );
}

export type CloseAsyncInput<
  TAccountUser extends string = string,
  TAccountUserVault extends string = string,
  TAccountUserVaultLamports extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  userVault?: Address<TAccountUserVault>;
  userVaultLamports?: Address<TAccountUserVaultLamports>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getCloseInstructionAsync<
  TAccountUser extends string,
  TAccountUserVault extends string,
  TAccountUserVaultLamports extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: CloseAsyncInput<
    TAccountUser,
    TAccountUserVault,
    TAccountUserVaultLamports,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserVault,
    TAccountUserVaultLamports,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userVault: { value: input.userVault ?? null, isWritable: true },
    userVaultLamports: {
      value: input.userVaultLamports ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.userVault.value) {
    accounts.userVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.userVaultLamports.value) {
    accounts.userVaultLamports.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 108, 97, 109, 112, 111, 114, 116, 115,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getAddressEncoder().encode(expectAddress(accounts.userVault.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userVault),
      getAccountMeta(accounts.userVaultLamports),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserVault,
    TAccountUserVaultLamports,
    TAccountSystemProgram
  >);
}

export type CloseInput<
  TAccountUser extends string = string,
  TAccountUserVault extends string = string,
  TAccountUserVaultLamports extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  userVault: Address<TAccountUserVault>;
  userVaultLamports: Address<TAccountUserVaultLamports>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCloseInstruction<
  TAccountUser extends string,
  TAccountUserVault extends string,
  TAccountUserVaultLamports extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: CloseInput<
    TAccountUser,
    TAccountUserVault,
    TAccountUserVaultLamports,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CloseInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountUserVault,
  TAccountUserVaultLamports,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userVault: { value: input.userVault ?? null, isWritable: true },
    userVaultLamports: {
      value: input.userVaultLamports ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userVault),
      getAccountMeta(accounts.userVaultLamports),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserVault,
    TAccountUserVaultLamports,
    TAccountSystemProgram
  >);
}

export type ParsedCloseInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    userVault: TAccountMetas[1];
    userVaultLamports: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CloseInstructionData;
};

export function parseCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      userVault: getNextAccount(),
      userVaultLamports: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCloseInstructionDataDecoder().decode(instruction.data),
  };
}
