/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const USER_VAULT_DISCRIMINATOR = new Uint8Array([
  23, 76, 96, 159, 210, 10, 5, 22,
]);

export function getUserVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(USER_VAULT_DISCRIMINATOR);
}

export type UserVault = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  userVaultBump: number;
  userVaultLamportsBump: number;
  totalDeposit: bigint;
  userVaultLamports: Address;
};

export type UserVaultArgs = {
  user: Address;
  userVaultBump: number;
  userVaultLamportsBump: number;
  totalDeposit: number | bigint;
  userVaultLamports: Address;
};

/** Gets the encoder for {@link UserVaultArgs} account data. */
export function getUserVaultEncoder(): FixedSizeEncoder<UserVaultArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["user", getAddressEncoder()],
      ["userVaultBump", getU8Encoder()],
      ["userVaultLamportsBump", getU8Encoder()],
      ["totalDeposit", getU64Encoder()],
      ["userVaultLamports", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: USER_VAULT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link UserVault} account data. */
export function getUserVaultDecoder(): FixedSizeDecoder<UserVault> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["user", getAddressDecoder()],
    ["userVaultBump", getU8Decoder()],
    ["userVaultLamportsBump", getU8Decoder()],
    ["totalDeposit", getU64Decoder()],
    ["userVaultLamports", getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link UserVault} account data. */
export function getUserVaultCodec(): FixedSizeCodec<UserVaultArgs, UserVault> {
  return combineCodec(getUserVaultEncoder(), getUserVaultDecoder());
}

export function decodeUserVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<UserVault, TAddress>;
export function decodeUserVault<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<UserVault, TAddress>;
export function decodeUserVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<UserVault, TAddress> | MaybeAccount<UserVault, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserVaultDecoder(),
  );
}

export async function fetchUserVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<UserVault, TAddress>> {
  const maybeAccount = await fetchMaybeUserVault(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<UserVault, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserVault(maybeAccount);
}

export async function fetchAllUserVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<UserVault>[]> {
  const maybeAccounts = await fetchAllMaybeUserVault(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<UserVault>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserVault(maybeAccount));
}

export function getUserVaultSize(): number {
  return 82;
}
