/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { VAULT_PROGRAM_ADDRESS } from "../programs";

/** VaultAlreadyInitialized: Cannot initialize, vault is already initialized */
export const VAULT_ERROR__VAULT_ALREADY_INITIALIZED = 0x1770; // 6000
/** NotVaultOwner: Cannot deposit, you are not owner of this vault */
export const VAULT_ERROR__NOT_VAULT_OWNER = 0x1771; // 6001
/** NotAuthorised: Cannot deposit, you are not authorised for this wallet account */
export const VAULT_ERROR__NOT_AUTHORISED = 0x1772; // 6002
/** MathOverflow: Math calculation overflow/underflow error */
export const VAULT_ERROR__MATH_OVERFLOW = 0x1773; // 6003
/** InvalidAmount: Invalid deposit amount */
export const VAULT_ERROR__INVALID_AMOUNT = 0x1774; // 6004
/** InsufficientFunds: Insufficient funds in the vault */
export const VAULT_ERROR__INSUFFICIENT_FUNDS = 0x1775; // 6005

export type VaultError =
  | typeof VAULT_ERROR__INSUFFICIENT_FUNDS
  | typeof VAULT_ERROR__INVALID_AMOUNT
  | typeof VAULT_ERROR__MATH_OVERFLOW
  | typeof VAULT_ERROR__NOT_AUTHORISED
  | typeof VAULT_ERROR__NOT_VAULT_OWNER
  | typeof VAULT_ERROR__VAULT_ALREADY_INITIALIZED;

let vaultErrorMessages: Record<VaultError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  vaultErrorMessages = {
    [VAULT_ERROR__INSUFFICIENT_FUNDS]: `Insufficient funds in the vault`,
    [VAULT_ERROR__INVALID_AMOUNT]: `Invalid deposit amount`,
    [VAULT_ERROR__MATH_OVERFLOW]: `Math calculation overflow/underflow error`,
    [VAULT_ERROR__NOT_AUTHORISED]: `Cannot deposit, you are not authorised for this wallet account`,
    [VAULT_ERROR__NOT_VAULT_OWNER]: `Cannot deposit, you are not owner of this vault`,
    [VAULT_ERROR__VAULT_ALREADY_INITIALIZED]: `Cannot initialize, vault is already initialized`,
  };
}

export function getVaultErrorMessage(code: VaultError): string {
  if (process.env.NODE_ENV !== "production") {
    return (vaultErrorMessages as Record<VaultError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isVaultError<TProgramErrorCode extends VaultError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    VAULT_PROGRAM_ADDRESS,
    code,
  );
}
